#!/usr/bin/env python3
"""
Turn the Cetizion workbook into SQL.

  python3 scripts/generate_seed.py "<path to .xlsx>"

Needs openpyxl, which is not part of the app (the server is Node, and this
script only runs by hand): pip install openpyxl

Writes two files next to db/schema.sql:

  db/seed.sql  — reference data plus every real row in the workbook
  db/demo.sql  — the workbook's own worked example (PO-77310 / PO-77455),
                 kept separate so the real seed stays free of invented
                 financial records

Rows whose Remarks read "Example - delete" are treated as the workbook's
examples, per its own Instructions tab.
"""

import re
import sys
from datetime import datetime
from pathlib import Path

import openpyxl

HEADER_ROW = 3
FIRST_DATA_ROW = 4

CURRENCY_SYMBOLS = {"₹": "INR", "€": "EUR", "$": "USD", "£": "GBP"}


def q(value):
    """Render a Python value as a SQL literal."""
    if value is None or value == "":
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, datetime):
        return "'%s'" % value.date().isoformat()
    return "'" + str(value).strip().replace("'", "''") + "'"


def text(cell):
    if cell is None:
        return None
    s = str(cell).strip()
    return s or None


def is_example(remarks):
    return bool(remarks) and "example" in str(remarks).lower()


def parse_money(raw):
    """'₹2,90,000' -> (290000.0, 'INR');  '833$' -> (833.0, 'USD')."""
    if raw is None or raw == "":
        return None, "INR"
    if isinstance(raw, (int, float)):
        return float(raw), "INR"
    s = str(raw).strip()
    currency = "INR"
    for symbol, code in CURRENCY_SYMBOLS.items():
        if symbol in s:
            currency = code
            break
    digits = re.sub(r"[^0-9.]", "", s)
    if not digits or digits == ".":
        return None, currency
    try:
        return float(digits), currency
    except ValueError:
        return None, currency


def rows(ws, key_col=1):
    """Yield (row_number, values) for rows whose key column is filled."""
    for i, row in enumerate(
        ws.iter_rows(min_row=FIRST_DATA_ROW, values_only=True), FIRST_DATA_ROW
    ):
        if row[key_col - 1] not in (None, ""):
            yield i, row


def insert(table, columns, records):
    if not records:
        return "-- no rows for %s\n" % table
    head = "INSERT INTO %s (%s) VALUES\n" % (table, ", ".join(columns))
    body = ",\n".join("  (%s)" % ", ".join(q(v) for v in r) for r in records)
    return head + body + ";\n"


def build(xlsx_path: Path):
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)
    seed, demo = [], []

    seed.append(
        "-- Generated by scripts/generate_seed.py from\n"
        "--   %s\n-- Do not edit by hand; regenerate instead.\n\nBEGIN;\n"
        % xlsx_path.name
    )

    # ---------------- reference data ----------------
    settings = [
        ("finance_email", "finance@cetizion.com",
         "Receives the 'raise invoice' worklist reminders."),
        ("hr_email", "hr@cetizion.com",
         "Owns the Travel Log, approvals and reimbursements."),
        # No default_advance_percent / default_delivery_percent: payment-terms
        # templates (#26) replaced them, and nothing read them in between.
        ("vendor_invoice_window_days", "15",
         "Travel vendor must invoice within this many days of the trip end."),
        ("default_vendor_payment_terms_days", "30",
         "Suggested terms for travel vendor invoices."),
        ("default_po_payment_terms_days", "30",
         "Default client payment terms on a new PO."),
    ]
    seed.append(insert("settings", ["key", "value", "notes"], settings))

    services = [
        (text(r[0]), i)
        for i, r in enumerate(
            wb["Services"].iter_rows(min_row=2, values_only=True), 1
        )
        if text(r[0])
    ]
    seed.append(insert("services", ["name", "sort_order"], services))

    tl = wb["Travel Lists"]
    vendors = [(text(r[0]),) for r in tl.iter_rows(min_row=2, values_only=True) if text(r[0])]
    categories = [(text(r[1]),) for r in tl.iter_rows(min_row=2, values_only=True) if text(r[1])]
    seed.append(insert("travel_vendors", ["name"], vendors))
    seed.append(insert("expense_categories", ["name"], categories))

    # ---------------- projects ----------------
    # The Project Tracker defines them; any project referenced by a won
    # quotation but missing there is created from that quotation, so the
    # foreign key never dangles.
    projects, seen = [], set()
    for _, r in rows(wb["Project Tracker"]):
        pid = text(r[0])
        if is_example(r[23]) or pid in seen:
            continue
        seen.add(pid)
        projects.append((pid, text(r[1]), text(r[2]), text(r[3]), text(r[22]),
                         text(r[4]), r[5], r[6], text(r[23])))

    quotations = []
    for _, r in rows(wb["Sales Tracker"], key_col=2):
        value, currency = parse_money(r[7])
        pid = text(r[10])
        if pid and pid not in seen:
            seen.add(pid)
            projects.append((pid, text(r[1]), text(r[3]), None, None,
                             text(r[4]), None, None,
                             "Created from quotation %s" % text(r[5])))
        quotations.append((
            text(r[5]), text(r[1]), text(r[2]), text(r[3]), text(r[4]),
            text(r[17]), r[6], value, currency,
            text(r[8]) or "Submitted",
            str(r[9]).strip().lower() == "yes" if r[9] else False,
            pid, text(r[16]),
        ))

    seed.append(insert(
        "projects",
        ["project_id", "client_name", "primary_service", "project_manager",
         "project_manager_email", "sales_person", "planned_start_date",
         "planned_delivery_date", "remarks"],
        projects,
    ))
    seed.append(insert(
        "quotations",
        ["quotation_no", "client_name", "contact_person", "service_quoted",
         "sales_person", "sales_person_email", "quotation_date",
         "quotation_value", "currency", "status", "po_received",
         "project_id", "remarks"],
        quotations,
    ))

    # ---------------- onboarding ----------------
    onboarding = [
        (text(r[0]), r[1], text(r[2]), text(r[3]), text(r[4]), text(r[9]),
         r[5], text(r[6]) or "Not Started", r[7], text(r[8]))
        for _, r in rows(wb["Onboarding"])
    ]
    seed.append(insert(
        "onboarding_tasks",
        ["project_id", "step_no", "stage", "step", "owner", "owner_email",
         "target_date", "status", "completed_date", "remarks"],
        onboarding,
    ))

    # ---------------- travel ----------------
    travel, travel_ids = [], set()
    for _, r in rows(wb["Travel Log"]):
        if is_example(r[20]):
            continue
        travel_ids.add(text(r[0]))
        travel.append((text(r[0]), text(r[1]), text(r[4]), text(r[5]),
                       text(r[6]), text(r[7]), text(r[8]), r[9], r[10],
                       text(r[11]), text(r[18]) or "HR Team",
                       text(r[19]) or "hr@cetizion.com", text(r[20])))
    seed.append(insert(
        "travel_logs",
        ["travel_id", "po_number", "service_delivered", "employee_name",
         "employee_email", "purpose", "destination", "travel_start_date",
         "travel_end_date", "arranged_by", "hr_owner", "hr_owner_email",
         "remarks"],
        travel,
    ))

    vendor_invoices = []
    for _, r in rows(wb["Travel Vendor Invoices"]):
        if is_example(r[20]) or text(r[1]) not in travel_ids:
            continue
        # Real rows carry the vendor's own invoice number in the ID column
        # and nothing else — HR still has to key in the amount.
        vendor_invoices.append((text(r[0]), text(r[1]),
                                text(r[8]) or text(r[0]), r[9], r[11],
                                r[12] or 30, r[15] or 0, r[16], text(r[20])))
    seed.append(insert(
        "travel_vendor_invoices",
        ["vendor_invoice_id", "travel_id", "vendor_invoice_no",
         "invoice_date", "invoice_amount", "payment_terms_days",
         "amount_paid", "payment_date", "remarks"],
        vendor_invoices,
    ))

    claims = []
    for _, r in rows(wb["Employee Expense Claims"]):
        if is_example(r[17]) or text(r[1]) not in travel_ids:
            continue
        claims.append((text(r[0]), text(r[1]), text(r[7]), text(r[8]),
                       r[9] or 0, r[10], text(r[11]) or "Submitted",
                       text(r[12]), r[13] or 0, r[14], text(r[17])))
    seed.append(insert(
        "employee_expense_claims",
        ["claim_id", "travel_id", "expense_category", "claim_month",
         "amount_claimed", "submission_date", "approval_status",
         "approved_by", "amount_reimbursed", "reimbursement_date", "remarks"],
        claims,
    ))

    seed.append(
        "\nSELECT setval(pg_get_serial_sequence('services','id'),"
        " GREATEST((SELECT MAX(id) FROM services), 1));\n"
    )
    seed.append("\nCOMMIT;\n")

    # ---------------- demo (the workbook's worked example) ----------------
    demo.append(
        "-- The workbook's own worked example (PO-77310 / PO-77455), kept\n"
        "-- out of seed.sql so the real data stays clean. Optional:\n"
        "--   npm run seed:demo\n\nBEGIN;\n"
    )
    demo.append(insert(
        "purchase_orders",
        ["po_number", "project_id", "po_date", "po_value",
         "payment_terms_days", "actual_initiation_date",
         "project_manager_email", "remarks"],
        [
            ("PO-77310", "PRJ-2026-001", "2026-05-20", 250000, 30,
             "2026-05-25", "diksha@cetizion.com", "Workbook example"),
            ("PO-77455", "PRJ-2026-001", "2026-06-02", 150000, 45,
             None, "diksha@cetizion.com", "Workbook example"),
        ],
    ))
    demo.append(insert(
        "po_services", ["po_number", "service", "service_value", "remarks"],
        [
            ("PO-77310", "GHG report preparation", 150000, "Workbook example"),
            ("PO-77310", "Assurance", 100000, "Workbook example"),
            ("PO-77455", "Supply chain audit", 150000, "Workbook example"),
        ],
    ))
    demo.append(insert(
        "payment_stages",
        ["po_number", "stage_no", "stage_name", "trigger_event",
         "stage_percent", "invoice_no", "invoice_date", "amount_received",
         "remarks"],
        [
            ("PO-77310", 1, "Advance (50%)", "On PO Registration", 0.5,
             "CTZ/INV/2026/021", "2026-05-26", 100000, "Workbook example"),
            ("PO-77310", 2, "On delivery (50%)", "On Delivery", 0.5,
             None, None, 0, "Workbook example"),
            ("PO-77455", 1, "Advance (50%)", "On PO Registration", 0.5,
             None, None, 0, "Workbook example"),
            ("PO-77455", 2, "On delivery (50%)", "On Delivery", 0.5,
             None, None, 0, "Workbook example"),
        ],
    ))
    demo.append("\nCOMMIT;\n")

    return "\n".join(seed), "\n".join(demo)


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: generate_seed.py <workbook.xlsx>")
    xlsx = Path(sys.argv[1]).expanduser().resolve()
    out = Path(__file__).resolve().parent.parent / "db"
    seed_sql, demo_sql = build(xlsx)
    (out / "seed.sql").write_text(seed_sql)
    (out / "demo.sql").write_text(demo_sql)
    print("wrote %s and %s" % (out / "seed.sql", out / "demo.sql"))


if __name__ == "__main__":
    main()
