-- Generated by scripts/generate_seed.py from
--   Cetizion_Sales_Expenses_and_Project_Tracker_final (2).xlsx
-- Do not edit by hand; regenerate instead.

BEGIN;

INSERT INTO settings (key, value, notes) VALUES
  ('finance_email', 'finance@cetizion.com', 'Receives the ''raise invoice'' worklist reminders.'),
  ('hr_email', 'hr@cetizion.com', 'Owns the Travel Log, approvals and reimbursements.'),
  ('default_advance_percent', '0.5', 'Suggested first-stage split. Actual % is set per stage.'),
  ('default_delivery_percent', '0.5', 'Suggested closing-stage split.'),
  ('vendor_invoice_window_days', '15', 'Travel vendor must invoice within this many days of the trip end.'),
  ('default_vendor_payment_terms_days', '30', 'Suggested terms for travel vendor invoices.'),
  ('default_po_payment_terms_days', '30', 'Default client payment terms on a new PO.');

INSERT INTO services (name, sort_order) VALUES
  ('Ecovadis Assessment (consulting)', 1),
  ('Assurance', 2),
  ('GHG report preparation', 3),
  ('Sustainability report Preparation', 4),
  ('ESG project', 5),
  ('ISO audits', 6),
  ('PSCI audits', 7),
  ('ASI audit', 8),
  ('Supply chain audit', 9),
  ('CBAM verification', 10);

INSERT INTO travel_vendors (name) VALUES
  ('MakeMyTrip Corporate'),
  ('Yatra for Business'),
  ('Thomas Cook (B2B)'),
  ('BCD Travel'),
  ('Cleartrip Corporate'),
  ('Direct booking (self)'),
  ('Holidays');

INSERT INTO expense_categories (name) VALUES
  ('Airfare'),
  ('Train fare'),
  ('Local transport / cab'),
  ('Hotel / lodging'),
  ('Meals'),
  ('Per diem / allowance'),
  ('Visa & documentation'),
  ('Miscellaneous');

INSERT INTO projects (project_id, client_name, primary_service, project_manager, project_manager_email, sales_person, planned_start_date, planned_delivery_date, remarks) VALUES
  ('PRJ-2026-001', 'Midal', 'LCA', 'Diksha', NULL, 'Ramesh', NULL, NULL, NULL),
  ('PRJ-2026-002', 'Assan Aluminium', 'ASI Surveillance Audit', NULL, NULL, 'Ramesh', NULL, NULL, 'Created from quotation CTZ/QT/2026/007'),
  ('PRJ-2026-003', 'Lee Pharma', 'EcoVadis, ISO 37001', NULL, NULL, 'Ramesh', NULL, NULL, 'Created from quotation CTZ/QT/2026/008'),
  ('PRJ-2026-004', 'Biophore', 'ISO 27001', NULL, NULL, 'Ramesh', NULL, NULL, 'Created from quotation CTZ/QT/2026/010'),
  ('PRJ-2026-005', 'Jain Green Technologies', 'Copper Mark Assurance and JDD', NULL, NULL, 'Ramesh', NULL, NULL, 'Created from quotation CTZ/QT/2026/011'),
  ('PRJ-2026-006', 'Biophore', 'Limited Assurance for SR Report', NULL, NULL, 'Ramesh', NULL, NULL, 'Created from quotation CTZ/QT/2026/013'),
  ('PRJ-2026-007', 'Hindalco - Kuppam', 'ASI Recertification & COC', NULL, NULL, 'Ramesh', NULL, NULL, 'Created from quotation CTZ/QT/2026/014');

INSERT INTO quotations (quotation_no, client_name, contact_person, service_quoted, sales_person, sales_person_email, quotation_date, quotation_value, currency, status, po_received, project_id, remarks) VALUES
  ('CTZ/QT/2026/001', 'Panda Aluminium', 'Haluk', 'ASI Certification', 'Ramesh', NULL, '2026-04-02', 9600.0, 'EUR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/002', 'Patanjali Foods', 'Amal', 'CSR Impact Assessment', 'Ramesh', NULL, '2026-04-02', 290000.0, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/003', 'Midal', 'Tripathi', 'LCA', 'Ramesh', NULL, '2026-04-06', 10700.0, 'EUR', 'Won - PO Received', true, 'PRJ-2026-001', NULL),
  ('CTZ/QT/2026/004', 'Hetero', 'Vishnu', 'LCA', 'Ramesh', NULL, '2026-04-07', 136000.0, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/005', 'Hetero', 'Vishnu', 'PCF', 'Ramesh', NULL, '2026-04-07', 80600.0, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/006', 'ACG', 'Akshay', 'ASI Certification & Chain of Custody', 'Ramesh', NULL, '2026-04-09', 510000.0, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/007', 'Assan Aluminium', 'Selvihan', 'ASI Surveillance Audit', 'Ramesh', NULL, '2026-04-09', 7950.0, 'EUR', 'Won - PO Received', true, 'PRJ-2026-002', NULL),
  ('CTZ/QT/2026/008', 'Lee Pharma', 'Yasar', 'EcoVadis, ISO 37001', 'Ramesh', NULL, '2026-04-09', 690000.0, 'INR', 'Won - PO Received', true, 'PRJ-2026-003', NULL),
  ('CTZ/QT/2026/009', 'BALCO', 'Divya', 'ASI Recertification', 'Ramesh', NULL, '2026-04-10', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/010', 'Biophore', 'Chandra Sekhar', 'ISO 27001', 'Ramesh', NULL, '2026-04-13', NULL, 'INR', 'Lost', false, 'PRJ-2026-004', NULL),
  ('CTZ/QT/2026/011', 'Jain Green Technologies', 'Kishan', 'Copper Mark Assurance and JDD', 'Ramesh', NULL, '2026-04-13', NULL, 'INR', 'Under Negotiation', false, 'PRJ-2026-005', NULL),
  ('CTZ/QT/2026/012', 'Trialco - PSW', 'Nitya - Sreehitha', 'ASI Certification', 'Ramesh', NULL, '2026-04-14', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/013', 'Biophore', 'Chandra Sekhar', 'Limited Assurance for SR Report', 'Ramesh', NULL, '2026-04-17', 180000.0, 'INR', 'Won - PO Received', true, 'PRJ-2026-006', NULL),
  ('CTZ/QT/2026/014', 'Hindalco - Kuppam', 'Ravi Prasada', 'ASI Recertification & COC', 'Ramesh', NULL, '2026-04-25', 950000.0, 'INR', 'Won - PO Received', true, 'PRJ-2026-007', NULL),
  ('CTZ/QT/2026/015', 'Aragen', 'Mali VR', 'Scope 3 GHG Emissions', 'Ramesh', NULL, '2026-04-27', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/016', 'Aragen', 'Mali VR', 'ISO 28001', 'Ramesh', NULL, '2026-04-27', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/017', 'Hindalco - Belur', 'Kundan Singh', 'ASI Recertification', 'Ramesh', NULL, '2026-04-28', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/018', 'Hetero', 'Vishnu', 'EcoVadis', 'Ramesh', NULL, '2026-04-28', 500000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/019', 'Hetero', 'Vishnu', 'ISO 28001 & 37001', 'Ramesh', NULL, '2026-04-28', 1498600.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/020', 'Vasudha Pharma', 'Visalakshmi', 'EcoVadis & other services', 'Ramesh', NULL, '2026-04-29', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/022', 'Arslan Aluminium', 'Harun', 'ASI Surveillance Audit', 'Ramesh', NULL, '2026-05-01', 8000.0, 'EUR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/023', 'Synthimed Labs', 'Pradip', 'ISO 20400', 'Ramesh', NULL, '2026-05-01', 175000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/024', 'EGYPTALUM', 'Ahmed/Mai', 'ASI Surveillance Audit', 'Ramesh', NULL, '2026-05-06', 21000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/025', 'Orion', 'Smitha/Vijay', 'ISO 50001', 'Ramesh', NULL, '2026-05-06', 50000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/026', 'Cohance', 'Nani Reddy', 'Assurance for BRSR & GRI Report', 'Ramesh', NULL, '2026-05-07', 390000.0, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/027', 'Jamna Auto/Jain Green', 'Praveen Lakhera', 'Reasonable Assurance for SR Report', 'Ramesh', NULL, '2026-05-08', 390000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/028', 'Honour', 'Anand', 'ISO 28000', 'Ramesh', NULL, '2026-05-15', 690000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/029', 'Orion', 'Smitha/Vijay', 'ISO 37001', 'Ramesh', NULL, '2026-05-17', 833.0, 'USD', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/030', 'Hetero', 'Vishnu', 'ISO 31000 & ISO 22301.', 'Ramesh', NULL, '2026-05-18', 765000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/031', 'ACG', 'Jyoti', 'PSCI', 'Ramesh', NULL, '2026-05-19', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/032', 'Hetero', 'Vishnu', 'PSCI', 'Ramesh', NULL, '2026-05-21', 900000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/033', 'AplApollo', 'Urmila', 'CBAM Quarterly Report', 'Ramesh', NULL, '2026-05-23', 228000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/034', 'Fishfa Rubbers', 'Rakesh', 'ISO and SBTI, Living wage,  SR with Design and Assurance', 'Ramesh', NULL, '2026-05-23', 500000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/035', 'Sterling Wilson', 'Neha Singh', 'SR Reasonable Assurance', 'Ramesh', NULL, '2026-05-25', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/036', 'Kreative Organics', 'Sreepathi', 'Ecovadis and other Services', 'Ramesh', NULL, '2026-05-25', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/037', 'Azico Biophore', 'Srikanth', 'Ecovadis and other Services', 'Ramesh', NULL, '2026-05-26', NULL, 'INR', 'On Hold', false, NULL, NULL),
  ('CTZ/QT/2026/038', 'Honour', 'Vishnu', 'PSCI', 'Ramesh', NULL, '2026-05-26', 765000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/039', 'Vasista Pharma Chem', 'Rajagopal', 'ISO 14 & 45 Recertification', 'Ramesh', NULL, '2026-05-26', NULL, 'INR', 'On Hold', false, NULL, NULL),
  ('CTZ/QT/2026/040', 'Orion', 'Smitha/Vijay', 'GHG Verification & SR Assurance Limited Level', 'Ramesh', NULL, '2026-05-28', 190000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/041', 'Dasami Labs', 'Vishnu', 'PSCI', 'Ramesh', NULL, '2026-05-28', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/042', 'Akums Drugs', 'Satya Prakash', 'PSCI', 'Ramesh', NULL, '2026-05-31', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/043', 'Akums Drugs', 'Satya Prakash', 'Hazop Study', 'Ramesh', NULL, '2026-05-31', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/044', 'Leap India', 'Sruthi', 'LEED Certification', 'Ramesh', NULL, '2026-06-03', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/045', 'Midal Cables', 'Tripathi', 'SR prep, design, Assurance and Digitalization', 'Ramesh', NULL, '2026-06-03', 42335.0, 'EUR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/046', 'Glochem & Chieron', 'Zahra', 'Ecovadis & Other Services', 'Ramesh', NULL, '2026-06-09', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/047', 'Sterile Copper', 'Rakesh', 'Copper mark Assurance', 'Ramesh', NULL, '2026-06-09', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/048', 'Morepen', 'Shalini', 'Ecovadis & Other Services', 'Ramesh', NULL, '2026-06-12', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/049', 'Kutch Copper', 'Kairavi', 'LME Certification', 'Ramesh', NULL, '2026-06-15', 688000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/050', 'Valency International Pte Ltd.', 'Dr. Uttam Sur', 'EcoVadis', 'Ramesh', NULL, '2026-06-16', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/051', 'Cohance', 'Nani Reddy', 'EcoVadis', 'Ramesh', NULL, '2026-06-23', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/052', 'Valency International Pte Ltd.', 'Dr. Uttam Sur', 'Hazard Area Classification', 'Ramesh', NULL, '2026-06-24', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/053', 'Valency International Pte Ltd.', 'Dr. Uttam Sur', 'HAZOP Study', 'Ramesh', NULL, '2026-06-24', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/054', 'ArtnCraft', 'Prateek', 'Decarbonization', 'Ramesh', NULL, '2026-07-01', NULL, 'INR', 'Lost', false, NULL, NULL),
  ('CTZ/QT/2026/055', 'Crow Danang', 'Ha Ma', 'ASI Surveillance Audit', 'Ramesh', NULL, '2026-07-01', NULL, 'INR', 'Submitted', false, NULL, NULL),
  ('CTZ/QT/2026/056', 'Hindalco', 'Narendra', 'Living Wage', 'Ramesh', NULL, '2026-07-07', NULL, 'INR', 'Submitted', false, NULL, NULL),
  ('CTZ/QT/2026/057', 'Aragen', 'Anand Pise', 'EcoVadis', 'Ramesh', NULL, '2026-07-07', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/058', 'Hindalco FRP', 'Mrutyunjaya', 'ASI Certification', 'Ramesh', NULL, '2026-07-07', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/059', 'IPCA', 'Dhaval', 'Amfori BSCI', 'Ramesh', NULL, '2026-07-07', 360000.0, 'INR', 'Won - PO Received', true, NULL, NULL),
  ('CTZ/QT/2026/060', 'Kreative Organics', 'Sripathi', 'ESG Strategy Development', 'Ramesh', NULL, '2026-07-16', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/061', 'Emcure', 'Goswami', 'Sustainability Assessment', 'Ramesh', NULL, '2026-07-16', NULL, 'INR', 'Under Negotiation', false, NULL, NULL),
  ('CTZ/QT/2026/062', 'Hindalco', 'Narendra', 'Modern Slavery', 'Ramesh', NULL, '2026-07-16', NULL, 'INR', 'Submitted', false, NULL, NULL);

INSERT INTO onboarding_tasks (project_id, step_no, stage, step, owner, owner_email, target_date, status, completed_date, remarks) VALUES
  ('PRJ-2026-001', 1, 'Onboarding', 'Purchase order(s) received and registered in the PO Register', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Done', NULL, NULL),
  ('PRJ-2026-001', 2, 'Onboarding', 'Services on each PO listed in the PO Services sheet', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Done', NULL, NULL),
  ('PRJ-2026-001', 3, 'Onboarding', 'Payment stages for each PO entered in the Payment Schedule', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Done', NULL, NULL),
  ('PRJ-2026-001', 4, 'Onboarding', 'Finance raises the stage-1 (advance) invoice per the PO payment terms', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Done', NULL, NULL),
  ('PRJ-2026-001', 5, 'Onboarding', 'Project manager and delivery team assigned', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Done', NULL, NULL),
  ('PRJ-2026-001', 6, 'Onboarding', 'Client kick-off meeting held; scope and delivery date confirmed', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Done', NULL, NULL),
  ('PRJ-2026-001', 7, 'Execution', 'Fieldwork / assessment / data collection completed', 'A. Verma', 'a.verma@cetizion.com', NULL, 'In Progress', NULL, NULL),
  ('PRJ-2026-001', 8, 'Execution', 'Draft deliverable shared with client for review', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Not Started', NULL, NULL),
  ('PRJ-2026-001', 9, 'Delivery', 'Final deliverable / report / certificate issued to client', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Not Started', NULL, NULL),
  ('PRJ-2026-001', 10, 'Delivery', 'Finance raises the on-delivery stage invoice(s)', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Not Started', NULL, NULL),
  ('PRJ-2026-001', 11, 'Closure', 'All stage invoices paid on time as per agreed terms - project closed', 'A. Verma', 'a.verma@cetizion.com', NULL, 'Not Started', NULL, NULL);

INSERT INTO travel_logs (travel_id, po_number, service_delivered, employee_name, employee_email, purpose, destination, travel_start_date, travel_end_date, arranged_by, hr_owner, hr_owner_email, remarks) VALUES
  ('TRV-2026-002', NULL, 'Ecovadis Assessment (consulting)', 'Diksha', 'diksha.sharma@cetizionverifica.com', NULL, 'Vizag', '2026-06-08', '2026-06-10', 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-003', NULL, 'Assurance', 'Ganga C Sharma', 'gangaacsharma@cetizionverifica.com', NULL, 'mumbai', '2026-06-08', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-004', NULL, NULL, 'Deepak Bhandari', 'deepakbhandari@ceteizionverifica.com', NULL, 'Hyderabad', '2026-06-17', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-005', NULL, NULL, 'Deepak Bhandari', 'deepakbhandari@ceteizionverifica.com', NULL, 'Delhi', '2026-06-21', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-006', NULL, NULL, 'SHYAM SHARMA', 'shyamsharma@cetizionverofica.com', NULL, 'Aurangabad', '2026-06-26', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-007', NULL, NULL, 'SHUBHAM GUPTA', 'shubhamgupta@cetizionverofica.com', NULL, 'Aurangabad', '2026-06-24', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-008', NULL, NULL, 'NARAYANAM RAJA SEKHAR', 'narayanamrajasekhar@cetizionverofica.com', NULL, 'Aurangabad', '2026-06-25', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-009', NULL, NULL, 'MOHAMMED HAYYAN SHAIKH ASLAM HAJWANI', 'mohammedhayyanshaikhaslamhajwani@cetizionverofica.com', NULL, 'Aurangabad', '2026-06-24', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-010', NULL, NULL, 'SHUBHAM GUPTA', 'shubhamgupta@cetizionverofica.com', NULL, 'lucknow', '2026-06-27', NULL, 'Holidays', 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-011', NULL, NULL, 'BURCU SIMSEK', 'burcusimsek2024@outlook.com', NULL, 'Muscut', '2026-07-04', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-012', NULL, NULL, 'Ganga C Sharma', 'gangaacsharma@cetizionverifica.com', NULL, 'Muscut', '2026-07-04', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-013', NULL, NULL, 'MUKESH MITTHAL', 'mukesh.mittal@cetizionverifica.com', NULL, 'Muscut', '2026-07-04', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-014', NULL, NULL, 'MUKESH MITTHAL', 'mukesh.mittal@cetizionverifica.com', NULL, 'delhi', '2026-07-08', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-015', NULL, NULL, 'Dilan Arslan', NULL, NULL, 'istanbul', '2026-07-04', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-016', NULL, NULL, 'BURCU SIMSEK', 'burcusimsek2024@outlook.com', NULL, 'istanbul', '2026-07-08', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-017', NULL, NULL, 'Ganga C Sharma', 'gangaacsharma@cetizionverifica.com', NULL, 'istanbul', '2026-07-08', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-018', NULL, NULL, 'Ganga C Sharma', 'gangaacsharma@cetizionverifica.com', NULL, 'delhi', '2026-07-08', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-019', NULL, NULL, 'Dilan Arslan', NULL, NULL, 'Ankara', '2026-07-08', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-020', NULL, NULL, 'NARAYANAM RAJA SEKHAR', 'narayanamrajasekhar@cetizionverofica.com', NULL, 'Hyderabad', '2026-06-28', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-021', NULL, NULL, 'MR SHYAM SHARMA', 'shyamsharma@cetizionverofica.com', NULL, 'Delhi', '2026-06-26', NULL, NULL, 'HR Team', 'hr@cetizion.com', NULL),
  ('TRV-2026-022', NULL, NULL, 'Dinesh', NULL, NULL, 'Hyderabad', '2026-07-08', NULL, NULL, 'HR Team', 'hr@cetizion.com', 'Flight Pune→Hyderabad, IndiGo, ₹20,669, booked 06-Jul-2026'),
  ('TRV-2026-023', NULL, NULL, 'Ganga C Sharma', NULL, NULL, 'Lagos', '2026-07-26', NULL, NULL, 'HR Team', 'hr@cetizion.com', 'Flight Delhi→Lagos, Ethiopian Airlines, ₹82,141, booked 06-Jul-2026'),
  ('TRV-2026-024', NULL, NULL, 'Dinesh', NULL, NULL, 'Delhi', '2026-07-20', NULL, NULL, 'HR Team', 'hr@cetizion.com', 'Flight Pune→Delhi, IndiGo, ₹9,426, booked 10-Jul-2026 (no service record on source sheet)'),
  ('TRV-2026-025', NULL, NULL, 'Rajshekar', NULL, NULL, 'Mumbai', '2026-07-12', NULL, NULL, 'HR Team', 'hr@cetizion.com', 'Flight Hyderabad→Mumbai, IndiGo, ₹11,182, booked 10-Jul-2026'),
  ('TRV-2026-026', NULL, NULL, 'Rajshekar', NULL, NULL, 'Hyderabad', '2026-07-15', NULL, NULL, 'HR Team', 'hr@cetizion.com', 'Flight Mumbai→Hyderabad, IndiGo, ₹7,009, booked 13-Jul-2026');

INSERT INTO travel_vendor_invoices (vendor_invoice_id, travel_id, vendor_invoice_no, invoice_date, invoice_amount, payment_terms_days, amount_paid, payment_date, remarks) VALUES
  ('HT/26-27/966', 'TRV-2026-003', 'HT/26-27/966', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/973', 'TRV-2026-004', 'HT/26-27/973', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1213', 'TRV-2026-005', 'HT/2627/1213', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/1208', 'TRV-2026-006', 'HT/26-27/1208', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/968', 'TRV-2026-007', 'HT/26-27/968', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/969', 'TRV-2026-008', 'HT/26-27/969', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/970', 'TRV-2026-009', 'HT/26-27/970', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/972', 'TRV-2026-010', 'HT/26-27/972', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/26-27/971', 'TRV-2026-011', 'HT/26-27/971', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1202', 'TRV-2026-012', 'HT/2627/1202', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1203', 'TRV-2026-013', 'HT/2627/1203', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1206', 'TRV-2026-014', 'HT/2627/1206', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1205', 'TRV-2026-016', 'HT/2627/1205', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1204', 'TRV-2026-017', 'HT/2627/1204', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1207', 'TRV-2026-018', 'HT/2627/1207', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1212', 'TRV-2026-019', 'HT/2627/1212', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1304', 'TRV-2026-020', 'HT/2627/1304', NULL, NULL, 30, 0, NULL, NULL),
  ('HT/2627/1208', 'TRV-2026-021', 'HT/2627/1208', NULL, NULL, 30, 0, NULL, NULL);

-- no rows for employee_expense_claims


SELECT setval(pg_get_serial_sequence('services','id'), GREATEST((SELECT MAX(id) FROM services), 1));


COMMIT;
